name: Trigger auto deployment for con-we-terra-nemrad-poc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/con-we-terra-nemrad-poc-AutoDeployTrigger-20837639-0929-4bf3-898e-754c2746abc5.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONWETERRANEMRADPOC_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: github.com/proxy255/fullcalendar-site-static.git
          registryUsername: ${{ secrets.CONWETERRANEMRADPOC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONWETERRANEMRADPOC_REGISTRY_PASSWORD }}
          containerAppName: con-we-terra-nemrad-poc
          resourceGroup: rg-we-terra-nemrad-poc
          imageToBuild: github.com/proxy255/fullcalendar-site-static.git/con-we-terra-nemrad-poc:${{ github.sha }}
          

     

